### ISSUE TITLE
Create a sumAsync function

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#10]
```js
sumAsync(3, 5, function (result) {
   console.log(result); // this should show 8
});
```

Define the `sumAsync` getting the following arguments:

 - the first number
 - the second number
 - the callback function

After one second, the sum result should be sent over the callback function.

**Comment by Toddsqui** [comment]
@IonicaBizau  I have added this function that you requested! :) :tada: :balloon: :truck:

**Comment by Toddsqui** [comment]
@IonicaBizau Please check the sumAsync.js file!! :+1: :8ball:

**Comment by Toddsqui** [comment]
cd21ef4

:+1:

**Comment by IonicaBizau** [comment]
:sparkles:
