### ISSUE TITLE
Improve the sumAsync example by creating a module out of it

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#11]
Read this about how to build local modules: http://www.sitepoint.com/understanding-module-exports-exports-node-js/

 1. Create another directory in the `examples` folder.
 2.  Create two files:

   - `sum.js` (this will be the sum module)
   - `index.js` (this will require the sum module–`sum.js`–and will call the exported function).

So, in `index.js` the code should look like:

```js
var sum = require("./sum");
sum(42, -2, function (r) {
 console.log("Result: " + r);
});
```

When running `node index.js` you should see `Result: 40` in the output.

Success! :joy:

**Comment by IonicaBizau** [comment]
This will help you to use local modules (local js files) in Node.js.

**Comment by Toddsqui** [comment]
@IonicaBizau The code that you provided above didn't recognize "sum" as a function, so I used the following code instead:

Index.js:

```
var sum = require("./sum.js");
console.log("Result: " + sum.sum(42, -2));
```

sum.js
```
module.exports.sum = function (a,b){
  return a + b;
};
```

Let me know what you think and if the other way is still possible! :construction_worker:

**Comment by IonicaBizau** [comment]
@Toddsqui Almost there! Use my code and instead of `module.exports.sum = ...` use `module.exports = function (a, b, callback) {...}`.

Don't forget to make it async.

**Comment by Toddsqui** [comment]
I changed the code. Now the index.js file looks like this:

```
var sum = require("./sum");
sum(42, -2, function (r) {
 console.log("Result: " + r);
});
```

While the sum. js file looks like this:
```
module.exports = function (a,b, callback ){
  var sum2 = a + b;
  callback(sum2);
};
```

Better? :fearful:

**Comment by IonicaBizau** [comment]
Perfect! :+1: :tada:
