### ISSUE TITLE
Create todd-square package

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#14]
It will make use of the `todd-prod` package.

``` js
var square = require("todd-square");

console.log(square(10));
// => 100
```

For debugging, refer to:

https://nodejs.org/api/debugger.html

---

Basically:

Add `debugger` in the code.

Then start the node process using `node debug your-script.js`:
- `n` (next): next line
- `c` (cont): continue until the next breakpoint/debugger
- `repl` switch on the interface to inspect variables
- `watch("variable")`: watch a variable

You can do always `help` to get the rest of the commands. :joy:

**Comment by Toddsqui** [comment]
@IonicaBizau [boom](https://github.com/Toddsqui/todd-square)! :love_letter:

**Comment by Toddsqui** [comment]
@IonicaBizau Also, added debugger! ;)

**Comment by IonicaBizau** [comment]
@Toddsqui Almost perfect. Use the `todd-prod` package to multiply the numbers. :smile:

**Comment by Toddsqui** [comment]
@IonicaBizau Done! :boom:  :smiley:

**Comment by IonicaBizau** [comment]
@Toddsqui Closing this! :smile: Hope you're doing well! :grin:
