### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#4]
Add some notes about the `examples` directories and what the apps are doing. :book:

**Comment by Toddsqui** [comment]
@IonicaBizau You mean a README file?

**Comment by IonicaBizau** [comment]
Exactly! :+1:

**Comment by IonicaBizau** [comment]
@Toddsqui This is not fixed yet––please explain each eample from the `examples` directory in the `README.md` file. :memo:

**Comment by Toddsqui** [comment]
@IonicaBizau You mean the fs code?
