### ISSUE TITLE
Implement a new http counter using `fs`

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#6]
So, since you know how to read and write files, you can create a new counter that will be based on the `fs` module.

 - [read the counter file](https://github.com/Toddsqui/learning-nodejs/blob/master/examples/http-fs-counter/index.js#L10)
 - [write the counter](https://github.com/Toddsqui/learning-nodejs/blob/master/examples/http-fs-counter/index.js#L23-L26)

**Comment by Toddsqui** [comment]
https://github.com/Toddsqui/learning-nodejs/commit/e25b352475659ee1c659d5ff3e9088df3952a8ea

**Comment by Toddsqui** [comment]
:wave:

**Comment by IonicaBizau** [comment]
:tada:
