### ISSUE TITLE
Generate a file containing all the integers from 1 to 1000

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#7]
Write a script to write in a file all the integer numbers between 1 and 1000, one per line.

```js
var myNumbers = "1\n2\n3\n"; // 1-3, one per line
// Here you should use a for loop to generate the myNumbers string
fs.writeFile("numbers.txt", myNumbers, function (err) { ... });
```

**Comment by Toddsqui** [comment]
@IonicaBizau Done! It says that I have reached the site 1001 times. :laughing:

**Comment by Toddsqui** [comment]
@IonicaBizau Files pushed already

**Comment by IonicaBizau** [comment]
No, no, forget the other example. Start a new example in the `examples` directory (create the `numbers` directory and create `index.js` there).

**Comment by Toddsqui** [comment]
@IonicaBizau Okay! Working on it now!
