### ISSUE TITLE
Put the require calls at the top of the file

### ISSUE THREAD

**Issue by IonicaBizau** [Toddsqui/learning-nodejs#8]
It's a good practice to keep the `require` calls in the first lines of the file.

For example, [this line](https://github.com/Toddsqui/learning-nodejs/blob/c480e57691250082200c0a2b0b6285ed745acc74/examples/numbers/index.js#L17) should be moved.

**Comment by Toddsqui** [comment]
@IonicaBizau But the fs doesn't do anything, does it?? :open_mouth:

**Comment by IonicaBizau** [comment]
@Toddsqui It loads the `fs` module. It's a good practice to load the modules on the first lines. :memo:

**Comment by Toddsqui** [comment]
Oh oh ! Okay I got it! :zap: !! Thanks!
